# Generated by Django 2.1.4 on 2019-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191117_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='school',
        ),
        migrations.AddField(
            model_name='userextension',
            name='nickname',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
