# Generated by Django 2.1.4 on 2019-11-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191117_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='nickname',
            field=models.CharField(default='', max_length=12),
        ),
    ]
