# Generated by Django 2.1.4 on 2019-11-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191117_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtension',
        ),
    ]
