# Generated by Django 2.1.4 on 2019-11-19 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='问题')),
                ('answer', mdeditor.fields.MDTextField(blank=True, max_length=10000, null=True, verbose_name='答案')),
                ('summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要')),
                ('font', models.BooleanField(blank=True, default=True, null=True, verbose_name='前端')),
                ('backend', models.BooleanField(blank=True, default=True, null=True, verbose_name='后端')),
                ('server', models.BooleanField(blank=True, default=True, null=True, verbose_name='服务器')),
                ('dev', models.BooleanField(blank=True, default=True, null=True, verbose_name='开发')),
                ('product', models.BooleanField(blank=True, default=True, null=True, verbose_name='部署')),
                ('date_time_last', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('date_time_first', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
