# Generated by Django 2.1.4 on 2019-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ponint',
            new_name='Dot',
        ),
    ]
