# Generated by Django 2.1.4 on 2019-11-14 12:46

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20191114_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='answer',
            field=mdeditor.fields.MDTextField(blank=True, max_length=10000, null=True, verbose_name='答案'),
        ),
    ]
