# Generated by Django 2.1.4 on 2019-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20191118_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='backend',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='后端'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='dev',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='开发'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='font',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='前端'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='product',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='server',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='服务器'),
        ),
    ]
