# Generated by Django 2.1.4 on 2019-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20191115_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
    ]
