# Generated by Django 2.1.4 on 2019-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_dot_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='labelone',
            field=models.CharField(blank=True, choices=[('font', '前端'), ('back', '后端'), ('server', '服务器'), ('dev', '开发'), ('product', '部署')], default='font', max_length=10, null=True, verbose_name='标签一'),
        ),
    ]
