# Generated by Django 2.1.4 on 2019-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20191115_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='labelfive',
            field=models.CharField(blank=True, choices=[('font', '前端'), ('back', '后端'), ('server', '服务器'), ('dev', '开发'), ('product', '部署')], default='font', max_length=10, null=True, verbose_name='标签五'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='labelfour',
            field=models.CharField(blank=True, choices=[('font', '前端'), ('back', '后端'), ('server', '服务器'), ('dev', '开发'), ('product', '部署')], default='font', max_length=10, null=True, verbose_name='标签四'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='labelthree',
            field=models.CharField(blank=True, choices=[('font', '前端'), ('back', '后端'), ('server', '服务器'), ('dev', '开发'), ('product', '部署')], default='font', max_length=10, null=True, verbose_name='标签三'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='labeltwo',
            field=models.CharField(blank=True, choices=[('font', '前端'), ('back', '后端'), ('server', '服务器'), ('dev', '开发'), ('product', '部署')], default='font', max_length=10, null=True, verbose_name='标签二'),
        ),
    ]
